version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=catalog

  web:
    build: .
    command: python /home/slavadan/docker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/slavadan/docker
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: